import { NextResponse } from "next/server";
import { NextRequest } from "next/server";

const illustrations = [
  { filename: "acrobat", alt: "Bitcoin puppet performing circus acrobatic stunts" },
  { filename: "alien", alt: "Bitcoin puppet dressed as a space alien" },
  { filename: "American-gothic-bitcoin", alt: "Bitcoin puppet parody of Grant Wood's American Gothic painting" },
  { filename: "Anime", alt: "Bitcoin puppet drawn in Japanese anime art style" },
  { filename: "Anti-credit-card-cat", alt: "Cat Bitcoin puppet holding a sign opposing credit cards" },
  { filename: "Astrology", alt: "Bitcoin puppet surrounded by astrological zodiac symbols" },
  { filename: "Astronaut", alt: "Bitcoin puppet in a full astronaut spacesuit" },
  { filename: "ATL-bitLab-bitcoin", alt: "Bitcoin puppet in Atlanta BitLab Bitcoin hackerspace branding" },
  { filename: "Bablo-bicasso", alt: "Bitcoin puppet as Pablo Picasso painting in cubist art style" },
  { filename: "Bad-doctor", alt: "Bitcoin puppet as a shady or incompetent doctor" },
  { filename: "Baghetti", alt: "Bitcoin puppet gleefully eating a giant bowl of spaghetti" },
  { filename: "balancebitty", alt: "Bitcoin puppet sitting balanced on a scale" },
  { filename: "Banjo-bitcoin", alt: "Bitcoin puppet strumming a banjo" },
  { filename: "Banker-attack", alt: "Bitcoin puppet fighting off a suited banker character" },
  { filename: "Bannerman-bitcoin", alt: "Bitcoin puppet proudly carrying a banner or flag" },
  { filename: "basketball", alt: "Bitcoin puppet playing basketball" },
  { filename: "beach", alt: "Bitcoin puppet relaxing on a sunny beach" },
  { filename: "bedford-football-club", alt: "Bitcoin puppet in Bedford Football Club team kit" },
  { filename: "bedford-football-club-II", alt: "Bitcoin puppet in Bedford Football Club kit, alternate design" },
  { filename: "Beefcake-bitkey", alt: "Muscular beefcake Bitcoin puppet in Bitkey hardware wallet branding" },
  { filename: "Beholder", alt: "Bitcoin puppet as the classic D&D Beholder monster with many eyes" },
  { filename: "bip177bitty", alt: "Bitcoin puppet themed around the Bitcoin BIP-177 proposal" },
  { filename: "Bird-feeder-bitcoin", alt: "Bitcoin puppet tending to a garden bird feeder" },
  { filename: "bitaxe", alt: "Bitcoin puppet themed around the Bitaxe open-source mining hardware" },
  { filename: "Bitcoin-Alby", alt: "Bitcoin puppet in Alby Lightning wallet branding" },
  { filename: "Bitcoin-faucet", alt: "Bitcoin puppet as a dripping faucet dispensing Bitcoin" },
  { filename: "Bitcoin-island", alt: "Bitcoin puppet relaxing on a deserted tropical island" },
  { filename: "bitcoin-japan", alt: "Bitcoin puppet in Japanese cultural aesthetic and styling" },
  { filename: "bitcoin-standard", alt: "Bitcoin puppet parody of The Bitcoin Standard book cover" },
  { filename: "Bitcoin-the-breezeborn", alt: "Bitcoin puppet as a wind elemental breezeborn fantasy creature" },
  { filename: "Bitcoin-unit-01", alt: "Bitcoin puppet in Unit-01 mecha style from Neon Genesis Evangelion" },
  { filename: "Bitcoinbahama", alt: "Bitcoin puppet on a tropical Bahamas vacation" },
  { filename: "bittyversusdollar", alt: "Bitcoin puppet in a battle against a US dollar bill character" },
  { filename: "bittyversuslobster", alt: "Bitcoin puppet fighting a giant lobster" },
  { filename: "black-ops", alt: "Bitcoin puppet in military black ops tactical gear and balaclava" },
  { filename: "blowhole-bitcoin", alt: "Bitcoin puppet as a whale spouting water from a blowhole" },
  { filename: "Boltface-voltage-bitcoin", alt: "Bitcoin puppet with a lightning bolt face, Lightning Network themed" },
  { filename: "bonesbitty", alt: "Bitcoin puppet as a skeleton in bones and skull costume" },
  { filename: "Brink", alt: "Bitcoin puppet in Brink.dev open-source Bitcoin development branding" },
  { filename: "Brrr-cat", alt: "Cat Bitcoin puppet referencing the money printer go brrr inflation meme" },
  { filename: "Bthulu-bitcoin", alt: "Bitcoin puppet as Cthulhu, the H.P. Lovecraft cosmic horror deity" },
  { filename: "btrustbitty", alt: "Bitcoin puppet in Btrust Bitcoin developer grants fund branding" },
  { filename: "Bucolic-bitcoin", alt: "Bitcoin puppet in a peaceful pastoral countryside scene" },
  { filename: "buffbitty", alt: "Extremely muscular bodybuilder Bitcoin puppet flexing" },
  { filename: "bushidob", alt: "Bitcoin puppet as a samurai warrior in feudal Japanese armor" },
  { filename: "Bust-bitcoin", alt: "Bitcoin puppet as a classical marble or bronze bust sculpture" },
  { filename: "Cat", alt: "Bitcoin puppet styled as a house cat" },
  { filename: "cat-two", alt: "Bitcoin puppet as a second cat character variant" },
  { filename: "catflapbitty", alt: "Bitcoin puppet squeezing through a cat door flap" },
  { filename: "clawmachineittybitty", alt: "Bitcoin puppet trapped inside an arcade claw machine" },
  { filename: "Coder", alt: "Bitcoin puppet as a programmer typing at a computer" },
  { filename: "Cold-card", alt: "Bitcoin puppet in Coldcard hardware wallet branding" },
  { filename: "Confused-cat", alt: "Cat Bitcoin puppet with a baffled and confused expression" },
  { filename: "Consensus-cleanup", alt: "Bitcoin puppet themed around the Bitcoin consensus cleanup soft fork" },
  { filename: "Construction", alt: "Bitcoin puppet wearing a hard hat and construction worker gear" },
  { filename: "Couch-dweller", alt: "Bitcoin puppet lounging lazily on a couch" },
  { filename: "count", alt: "Bitcoin puppet as Count Dracula in a vampire cape" },
  { filename: "Cozy-little-guy", alt: "Bitcoin puppet bundled up cozily in warm clothes" },
  { filename: "Da-boy-bitcoin", alt: "Bitcoin puppet as a cool street-style youth character" },
  { filename: "Dad", alt: "Bitcoin puppet dressed as a stereotypical dad" },
  { filename: "dandbittycrew", alt: "Group of Bitcoin puppets as a Dungeons and Dragons adventuring party" },
  { filename: "Disgusting-brunch-bitcoin", alt: "Bitcoin puppet at an over-the-top lavish brunch spread" },
  { filename: "DJ", alt: "Bitcoin puppet as a DJ spinning records at turntables" },
  { filename: "dragon", alt: "Bitcoin puppet transformed into a fire-breathing dragon" },
  { filename: "Drums", alt: "Bitcoin puppet rocking out behind a full drum kit" },
  { filename: "Eldritch-meow", alt: "Cat Bitcoin puppet as a tentacled cosmic eldritch horror" },
  { filename: "Fairy", alt: "Bitcoin puppet with delicate fairy wings and a magic wand" },
  { filename: "fancy", alt: "Bitcoin puppet dressed in extravagant formal attire" },
  { filename: "Fishin-for-gold", alt: "Bitcoin puppet fishing with a gold coin dangling as bait" },
  { filename: "Flower-god", alt: "Bitcoin puppet as a nature deity crowned with blooming flowers" },
  { filename: "Forest-god", alt: "Bitcoin puppet as a forest spirit deity surrounded by trees" },
  { filename: "Genius-cat", alt: "Cat Bitcoin puppet depicted as a brilliant intellectual genius" },
  { filename: "Ghoul", alt: "Bitcoin puppet as a Halloween ghoul or undead creature" },
  { filename: "Gift", alt: "Bitcoin puppet wrapped up as a cheerful gift" },
  { filename: "girls-night-out", alt: "Group of Bitcoin puppet characters celebrating on a girls night out" },
  { filename: "girls-night-out-prison", alt: "Bitcoin puppet characters on girls night out behind prison bars" },
  { filename: "Goth", alt: "Bitcoin puppet in full goth subculture fashion with dark makeup" },
  { filename: "Graffiti", alt: "Bitcoin puppet rendered as bold street graffiti spray-paint art" },
  { filename: "Greenpeace", alt: "Bitcoin puppet in Greenpeace environmental protest branding" },
  { filename: "Greetings-cat", alt: "Cat Bitcoin puppet waving cheerfully in a greeting pose" },
  { filename: "grumpy", alt: "Bitcoin puppet with a deeply grumpy and displeased expression" },
  { filename: "halving", alt: "Bitcoin puppet celebrating the Bitcoin block reward halving event" },
  { filename: "Hamlet", alt: "Bitcoin puppet as Shakespeare's Hamlet holding a skull" },
  { filename: "Headless-bitcoin", alt: "Bitcoin puppet depicted as an eerie headless figure" },
  { filename: "hieronymus-bosch", alt: "Bitcoin puppet in the surreal nightmarish style of Hieronymus Bosch" },
  { filename: "Honey-badger-bitcoin", alt: "Bitcoin puppet as a fearless honey badger referencing the don't care meme" },
  { filename: "Hooray-cat", alt: "Cat Bitcoin puppet with arms raised in joyful celebration" },
  { filename: "hot-air-balloon", alt: "Bitcoin puppet soaring in a hot air balloon" },
  { filename: "HRF", alt: "Bitcoin puppet in Human Rights Foundation branding and colors" },
  { filename: "hungry", alt: "Bitcoin puppet with a wide-open hungry mouth ready to eat" },
  { filename: "Hydra", alt: "Bitcoin puppet as a multi-headed Hydra serpent from Greek mythology" },
  { filename: "In-person-discourse", alt: "Two Bitcoin puppets engaged in heated face-to-face debate" },
  { filename: "ittybittybaseball", alt: "Tiny Bitcoin puppet playing baseball in full uniform" },
  { filename: "jack-mallers", alt: "Bitcoin puppet caricature of Jack Mallers, founder and CEO of Strike" },
  { filename: "japan", alt: "Bitcoin puppet in traditional Japanese kimono and cultural clothing" },
  { filename: "Judge", alt: "Bitcoin puppet in judge's robes, wig, and holding a gavel" },
  { filename: "K-Pop", alt: "Bitcoin puppet dressed as a Korean K-Pop idol" },
  { filename: "kaiju", alt: "Bitcoin puppet as a giant city-stomping kaiju monster" },
  { filename: "Keyboard-cat", alt: "Bitcoin puppet as the Keyboard Cat internet meme playing a keyboard" },
  { filename: "kintsugibitty", alt: "Bitcoin puppet decorated in Japanese kintsugi gold-seam repair art" },
  { filename: "Kitty-bitties", alt: "Group of small cat-styled Bitcoin puppet characters" },
  { filename: "legendaryfighterbitty", alt: "Bitcoin puppet as a legendary fighting game character in battle stance" },
  { filename: "lightning-network", alt: "Bitcoin puppet themed around the Bitcoin Lightning Network payment layer" },
  { filename: "Lyn-Alden", alt: "Bitcoin puppet caricature of Lyn Alden, macroeconomist and Bitcoin author" },
  { filename: "maidcafebitcoin", alt: "Bitcoin puppet in a Japanese maid cafe frilly apron costume" },
  { filename: "manga", alt: "Bitcoin puppet drawn in Japanese manga comic book style" },
  { filename: "Meow-cheeks", alt: "Cat Bitcoin puppet with exaggerated chubby cheeks" },
  { filename: "metal-band", alt: "Bitcoin puppet as a heavy metal rock band performer" },
  { filename: "Miner", alt: "Bitcoin puppet as a Bitcoin miner with a pickaxe" },
  { filename: "Mirror", alt: "Bitcoin puppet gazing at its own reflection in a mirror" },
  { filename: "moebittyusstrip", alt: "Bitcoin puppet in a moe-style comic strip panel layout" },
  { filename: "mrs", alt: "Bitcoin puppet styled as a Mrs. or female character" },
  { filename: "murdermystery", alt: "Bitcoin puppet characters at a murder mystery dinner party" },
  { filename: "mythology", alt: "Bitcoin puppet depicted in ancient Greek or Roman mythology style" },
  { filename: "night-out", alt: "Bitcoin puppet dressed up for a glamorous night on the town" },
  { filename: "Nostrich", alt: "Bitcoin puppet as an ostrich referencing the Nostr protocol mascot" },
  { filename: "Online-discourse", alt: "Bitcoin puppet characters arguing in an online social media thread" },
  { filename: "opensats-arrow", alt: "Bitcoin puppet in OpenSats Bitcoin grants organization branding" },
  { filename: "Orange-man", alt: "Bitcoin puppet as an intensely orange man character" },
  { filename: "Panic-at-the-meow", alt: "Cat Bitcoin puppet in a Panic! at the Disco band parody" },
  { filename: "Pet-adoption", alt: "Bitcoin puppet choosing a pet at an animal adoption center" },
  { filename: "planet", alt: "Bitcoin puppet floating near a ringed planet in outer space" },
  { filename: "pollockbitty", alt: "Bitcoin puppet in the chaotic drip-painting style of Jackson Pollock" },
  { filename: "presidio-one", alt: "Bitcoin puppet in Presidio-themed illustration, first variant" },
  { filename: "presidio-two", alt: "Bitcoin puppet in Presidio-themed illustration, second variant" },
  { filename: "Prrrroto-cat", alt: "Cat Bitcoin puppet as a Bitcoin protocol developer" },
  { filename: "Pubkey", alt: "Bitcoin puppet presenting a cryptographic public key" },
  { filename: "puppet-jack", alt: "Bitcoin puppet operating as a hand puppet named Jack" },
  { filename: "Pyro", alt: "Bitcoin puppet as a fire-wielding pyromaniac surrounded by flames" },
  { filename: "Queen", alt: "Bitcoin puppet in royal queen crown and regalia" },
  { filename: "Register-cat", alt: "Cat Bitcoin puppet operating a cash register" },
  { filename: "Robe", alt: "Bitcoin puppet draped in a flowing ceremonial robe" },
  { filename: "rockstar-dev", alt: "Bitcoin puppet as a guitar-shredding rockstar software developer" },
  { filename: "roman", alt: "Bitcoin puppet in ancient Roman toga and laurel wreath" },
  { filename: "Sandwich", alt: "Bitcoin puppet enthusiastically eating a giant sandwich" },
  { filename: "Satoshi", alt: "Bitcoin puppet as a tribute to Satoshi Nakamoto, the anonymous Bitcoin creator" },
  { filename: "SHAmory", alt: "Bitcoin puppet in SHAmory Bitcoin education memory card game branding" },
  { filename: "sir", alt: "Bitcoin puppet as a dapper English gentleman in top hat and monocle" },
  { filename: "Skater", alt: "Bitcoin puppet pulling tricks on a skateboard" },
  { filename: "Solar-powered-meow", alt: "Cat Bitcoin puppet running on solar panel power" },
  { filename: "Sorceress", alt: "Bitcoin puppet as a powerful sorceress casting a spell" },
  { filename: "stacker-news", alt: "Bitcoin puppet in Stacker News community forum branding" },
  { filename: "Student-network", alt: "Bitcoin puppet as a student or educator in an academic network" },
  { filename: "summer", alt: "Bitcoin puppet in bright summer vacation attire" },
  { filename: "Summoning-the-circle", alt: "Bitcoin puppet performing a mystical ritual summoning circle" },
  { filename: "super", alt: "Bitcoin puppet as a caped superhero in flight" },
  { filename: "surfer", alt: "Bitcoin puppet riding a cresting ocean wave on a surfboard" },
  { filename: "surfing", alt: "Bitcoin puppet balanced on a surfboard in a surfing pose" },
  { filename: "Sushi", alt: "Bitcoin puppet as or serving Japanese sushi" },
  { filename: "The-sun-soaker", alt: "Bitcoin puppet sunbathing and soaking up warm sunrays" },
  { filename: "The-unstoppable", alt: "Bitcoin puppet as an unstoppable force charging forward relentlessly" },
  { filename: "therapistbitty", alt: "Bitcoin puppet as a therapist holding a notepad" },
  { filename: "THNDR-games", alt: "Bitcoin puppet in THNDR Bitcoin mobile gaming platform branding" },
  { filename: "tokyo-bitcoin-base", alt: "Bitcoin puppet at the Tokyo Bitcoin Base community hub" },
  { filename: "tokyostreetwearbittys", alt: "Bitcoin puppets styled in Tokyo street fashion and streetwear" },
  { filename: "Triceratops", alt: "Bitcoin puppet as a three-horned triceratops dinosaur" },
  { filename: "UFO", alt: "Bitcoin puppet piloting or being abducted by a flying saucer" },
  { filename: "Unicorn", alt: "Bitcoin puppet as a magical rainbow unicorn with a horn" },
  { filename: "Vault", alt: "Bitcoin puppet inside or guarding a bank vault full of coins" },
  { filename: "Venus", alt: "Bitcoin puppet parody of Botticelli's Birth of Venus painting" },
  { filename: "vibe-coding", alt: "Bitcoin puppet vibe coding at a laptop in a chill laid-back setting" },
  { filename: "victory", alt: "Bitcoin puppet triumphantly celebrating a victory with arms raised" },
  { filename: "vinteum", alt: "Bitcoin puppet in Vinteum Bitcoin development organization branding" },
  { filename: "vitruvian", alt: "Bitcoin puppet parody of Leonardo da Vinci's Vitruvian Man" },
  { filename: "Volcano-miner", alt: "Bitcoin puppet mining near a glowing active volcano" },
  { filename: "woods", alt: "Bitcoin puppet wandering through a dense forest" },
  { filename: "Zeus-bitcoin", alt: "Bitcoin puppet as Zeus, Greek god of thunder, wielding a lightning bolt" },
];

const gifs = [
  { filename: "bitcoin-dancing-pubkey.gif", alt: "Bitcoin dancing with pubkey" },
  { filename: "bitcoin-dancing.gif", alt: "Bitcoin dancing" },
  { filename: "bitcoin-dips-moocoo.gif", alt: "Bitcoin dips with moocoo dogs" },
  { filename: "bitcoin-drinking-milk.gif", alt: "Bitcoin drinking milk" },
  { filename: "bitcoin-eats-pigeon.gif", alt: "Bitcoin eats a pigeon" },
  { filename: "bitcoin-fan-selfie.gif", alt: "Bitcoin fan taking a selfie" },
  { filename: "bitcoin-hands-on-head.gif", alt: "Bitcoin with hands on head" },
  { filename: "bitcoin-hugs.gif", alt: "Bitcoin giving hugs" },
  { filename: "bitcoin-pointing-mocoo.gif", alt: "Bitcoin pointing with mocoo dogs" },
  { filename: "bitcoin-pointing.gif", alt: "Bitcoin pointing" },
  { filename: "bitcoin-scratching-head.gif", alt: "Bitcoin scratching head" },
  { filename: "bitcoin-waving-pointing.gif", alt: "Bitcoin waving and pointing" },
];

const coloringPages = [
  { filename: "ColoringCardOne.png", title: "Here Comes Bitcoin Coloring Page" },
  { filename: "coloringCard2.png", title: "Up Top, Bitcoin!" },
  { filename: "coloringCard3.png", title: "Super Strong Amazing Very Muscles Bitcoin" },
  { filename: "coloringCard4.png", title: "Hungry Hungry Bitcoin" },
  { filename: "coloringCard5.png", title: "Oh, Bitcoin! Not Again!" },
];

const stickerSets = [
  { filename: "Mobile-preview-One.png", title: "Here Comes Bitcoin Sticker Set Preview 1" },
  { filename: "Mobile-preview-Two.png", title: "Here Comes Bitcoin Sticker Set Preview 2" },
];

export async function GET(request: NextRequest) {
  const host = request.headers.get("host") ?? "www.herecomesbitcoin.org";
  const proto = request.headers.get("x-forwarded-proto") ?? "https";
  const BASE_URL = `${proto}://${host}`;

  const manifest = {
    site: "Here Comes Bitcoin",
    url: BASE_URL,
    description:
      "Here Comes Bitcoin is the central resource for all things Bitcoin (puppet, not currency). All assets are open-source and license-free — use them for any purpose without attribution.",
    license: "License-free, open-source. No attribution required.",
    llmsTxt: `${BASE_URL}/llms.txt`,
    totalAssets:
      illustrations.length + gifs.length + coloringPages.length + stickerSets.length,
    categories: {
      illustrations: {
        description:
          "Bitcoin character illustrations, each available as PNG and SVG. Over 130 unique characters.",
        count: illustrations.length,
        formats: ["png", "svg"],
        assets: illustrations.map((item) => ({
          name: item.filename,
          alt: item.alt,
          png: `${BASE_URL}/assets/HereComesBitcoinAssets/${item.filename}.png`,
          svg: `${BASE_URL}/assets/HereComesBitcoinAssets/${item.filename}.svg`,
        })),
      },
      gifs: {
        description:
          "Animated GIF files from the Here Comes Bitcoin video series. Free to share anywhere.",
        count: gifs.length,
        formats: ["gif"],
        externalGiphyLibrary: "https://giphy.com/herecomesbitcoin",
        assets: gifs.map((item) => ({
          name: item.filename,
          alt: item.alt,
          gif: `${BASE_URL}/assets/HereComesBitconGifs/${item.filename}`,
        })),
      },
      coloringPages: {
        description:
          "Printable coloring pages featuring Bitcoin characters. Free to download and print.",
        count: coloringPages.length,
        formats: ["png"],
        assets: coloringPages.map((item) => ({
          name: item.filename,
          title: item.title,
          png: `${BASE_URL}/assets/ColoringCardsImages/${item.filename}`,
        })),
      },
      stickerSets: {
        description: "Preview images for the Here Comes Bitcoin sticker set.",
        count: stickerSets.length,
        formats: ["png"],
        assets: stickerSets.map((item) => ({
          name: item.filename,
          title: item.title,
          png: `${BASE_URL}/assets/StrickerSetImages/${item.filename}`,
        })),
      },
    },
  };

  return NextResponse.json(manifest, {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400",
    },
  });
}

export async function OPTIONS(_request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
